import streamlit as st

st.set_page_config(
    page_title="Home",
    page_icon="👋",
)

st.write("# BEM VINDO AO APLICATIVO DE ANÁLISE DE DADOS DA MULTSISTEM! 👋")

st.sidebar.success("Select a demo above.")

st.markdown(
    """
O APLICATIVO DE ANÁLISE DE DADOS DA MULTISTEM TEM COMO OBJETIVO A VISUALIZAÇÃO INTERATIVA DOS DADOS DA SUA EMPRESA EM TEMPO REAL. NOSSO OBJETIVO É FACILITAR A TOMADA DE DECISÃO DO NOSSO CLIENTE ATRAVÉS DE VISUALIZAÇÕES E INSIGHTS PODEROSOS SOBRE AS ATIVIDADES DO SEU NEGÓCIO. E O NOSSO CLIENTE AINDA PODERÁ SUGERIR ANÁLISES PERSONALIZADAS PARA SEU APLICATIVO, TORNANDO NOSSO PRODUTO MAIS FLEXÍVEL E MAIS PRÓXIMO DA REALIDADE DO NOSSO CLIENTE.
APROVEITE!

  
    """
)